#!/usr/bin/env zsh
# pack_resources.sh
# -----------------
# Zips the *non-regenerable, non-downloadable* resources into resources.zip,
# ready for upload to Google Drive.
#
# What IS packed (~4–5 GB):
#   resources/models/           custom YOLO / engine files
#   resources/weights/          extra model weights
#   resources/recordings/       raw camera recordings
#   resources/uavdt_sample/     UAVDT supervisely sample
#   resources/visdrone/         VisDrone-DET (no reliable public mirror)
#   resources/video_test/*.mp4  hand-picked test clips (loose files only)
#
# What is NOT packed (too large or already auto-downloaded):
#   resources/M3OT/              – request from authors, 11 GB
#   resources/uav123/            – official benchmark, 9 GB
#   resources/dronecrowd/        – handled by download_resources.py, 22 GB
#   resources/visdrone_mot/      – handled by download_resources.py, 22 GB
#   resources/video_test/*_annotated/  – regenerated by scratch/ scripts, 17 GB
#
# Usage:
#   ./pack_resources.sh
#
# Then upload resources.zip to Google Drive:
#   1. Go to drive.google.com → New → File upload → resources.zip
#   2. Right-click → Share → Anyone with the link (Viewer)
#   3. Copy the file ID from the share URL:
#        https://drive.google.com/file/d/<FILE_ID>/view?usp=sharing
#   4. Paste FILE_ID into download_resources.py  →  RESOURCES_ZIP_ID = "..."
#   5. Commit and push:
#        git add download_resources.py pack_resources.sh
#        git commit -m "update gdrive resource id"
#        git push

set -e
cd "$(dirname "$0")"

OUTFILE="resources.zip"

# Remove stale zip if present
[[ -f "$OUTFILE" ]] && rm "$OUTFILE"

echo "Packing resources → $OUTFILE ..."
echo "  Including: models, weights, recordings, uavdt_sample, visdrone (DET), video_test/*.mp4"

zip -r "$OUTFILE" \
  resources/models \
  resources/weights \
  resources/recordings \
  resources/uavdt_sample \
  resources/visdrone \
  -x "*.DS_Store" "resources/**/__pycache__/*"

# Add only loose MP4s from video_test (exclude subdirectories)
zip "$OUTFILE" resources/video_test/*.mp4 -x "*.DS_Store"

SIZE=$(du -sh "$OUTFILE" | cut -f1)
echo ""
echo "Done.  $OUTFILE  ($SIZE)"
echo ""
echo "Next steps:"
echo "  1. Upload $OUTFILE to Google Drive"
echo "  2. Share as 'Anyone with the link can view'"
echo "  3. Copy the file ID from the share URL and paste into download_resources.py"
echo "     RESOURCES_ZIP_ID = \"<new file id>\""
echo "  4. git add download_resources.py && git commit -m 'update resources zip id' && git push"
